"""make_notification_user_title_id_nullable

Revision ID: ed2c395fd60a
Revises: 17df441d6f0d
Create Date: 2026-02-20 19:38:17.746431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2c395fd60a'
down_revision: Union[str, Sequence[str], None] = '17df441d6f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'user_title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'user_title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
