"""add_genres_and_review

Revision ID: 0c4fbe9bb879
Revises: ed3a0fb4af93
Create Date: 2026-02-05 13:49:06.977842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c4fbe9bb879'
down_revision: Union[str, Sequence[str], None] = 'ed3a0fb4af93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('user_titles', sa.Column('review_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_titles', 'review_text')
    op.drop_column('titles', 'genres')
    # ### end Alembic commands ###
