"""add_titles

Revision ID: 0ea6261a4de0
Revises: 8fc1aed22167
Create Date: 2026-02-05 12:37:21.433376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea6261a4de0'
down_revision: Union[str, Sequence[str], None] = '8fc1aed22167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('GAME', 'MOVIE', 'SERIES', 'ANIME', name='titlecategory'), nullable=False),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_titles'))
    )
    op.create_index(op.f('ix_titles_name'), 'titles', ['name'], unique=False)
    op.create_table('user_titles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PLAYING', 'WATCHING', 'DROPPED', 'PLANNED', 'ON_HOLD', name='usertitlestatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_user_titles_title_id_titles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_titles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_titles')),
    sa.UniqueConstraint('user_id', 'title_id', name='uq_user_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_titles')
    op.drop_index(op.f('ix_titles_name'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
