"""add_external_id_to_titles

Revision ID: 2e3fde7ebd45
Revises: 0ea6261a4de0
Create Date: 2026-02-05 13:27:17.605813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3fde7ebd45'
down_revision: Union[str, Sequence[str], None] = '0ea6261a4de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_titles_external_id'), 'titles', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titles_external_id'), table_name='titles')
    op.drop_column('titles', 'external_id')
    # ### end Alembic commands ###
