"""add_finished_at

Revision ID: 7de87312cfab
Revises: 0c4fbe9bb879
Create Date: 2026-02-08 13:14:10.925498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de87312cfab'
down_revision: Union[str, Sequence[str], None] = '0c4fbe9bb879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_titles', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_titles', 'finished_at')
    # ### end Alembic commands ###
