"""add_title_screenshots

Revision ID: 04bbf33bc74e
Revises: ed2c395fd60a
Create Date: 2026-02-25 09:35:23.165851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bbf33bc74e'
down_revision: Union[str, Sequence[str], None] = 'ed2c395fd60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_screenshots',
    sa.Column('user_title_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_title_id'], ['user_titles.id'], name=op.f('fk_title_screenshots_user_title_id_user_titles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_screenshots'))
    )
    op.create_index(op.f('ix_title_screenshots_user_title_id'), 'title_screenshots', ['user_title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_screenshots_user_title_id'), table_name='title_screenshots')
    op.drop_table('title_screenshots')
    # ### end Alembic commands ###
