"""add is_spoiler to user_titles

Revision ID: beea689a909e
Revises: 7de87312cfab
Create Date: 2026-02-12 09:49:01.383951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beea689a909e'
down_revision: Union[str, Sequence[str], None] = '7de87312cfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_titles', sa.Column('is_spoiler', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_titles', 'is_spoiler')
    # ### end Alembic commands ###
